name: Java CI Build and Test

# Trigger this workflow on every push to any branch
on: [push]

jobs:
  build:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # Step 3: Grant execute permission for gradlew (important on Linux runners)
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build the application with Gradle wrapper
      - name: Build with Gradle
        # Run the assemble task as required by Jenkinsfile Stage 'Build'
        run: ./gradlew assemble

      # Step 5: Test the application with Gradle wrapper
      - name: Test with Gradle
        # Run the test task as required by Jenkinsfile Stage 'Test'
        run: ./gradlew test