name: Java CI Build and Test

# Trigger this workflow on every push to any branch
on: [push]

jobs:
  build:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest # This was reported as line 9

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # Step 3: Set up Node.js 16
      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: client-app/yarn.lock # Specify path to lock file for caching

      # Step 4: Grant execute permission for gradlew (important on Linux runners)
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 5: Build the application with Gradle wrapper
      - name: Build with Gradle
        run: ./gradlew assemble

      # Step 6: Test the application with Gradle wrapper
      - name: Test with Gradle
        run: ./gradlew test