name: Java CI Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # *** ADD THIS NEW STEP ***
      - name: Set up Node.js 16 # Use Node.js version 16
        uses: actions/setup-node@v4 # Use Node setup action
        with:
          node-version: 16       # Specify version 16
          cache: 'yarn'          # Cache yarn dependencies

      # Step below was Step 3, now Step 4
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step below was Step 4, now Step 5
      - name: Build with Gradle
        run: ./gradlew assemble

      # Step below was Step 5, now Step 6
      - name: Test with Gradle
        run: ./gradlew test

        cache: 'yarn'            # Cache yarn dependencies
        # *** ADD THIS LINE ***
        cache-dependency-path: client-app/yarn.lock # Specify path to lock file for caching

              # Set up Node.js 16
      - name: Set up Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: client-app/yarn.lock # Tell cache where yarn.lock is