name: Java CI Build and Test (Simulated Jenkins)

# Trigger this workflow on every push to any branch
on: [push]

jobs:
  build:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code so the workflow can access it
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use a recent version

      # Step 2: Set up JDK 8, which is required by this project
      - name: Set up JDK 8
        uses: actions/setup-java@v4 # Use a recent version
        with:
          java-version: '8'        # Specify Java 8
          distribution: 'temurin'  # Specify distribution (Adoptium Temurin is common)
          cache: 'gradle'          # Cache Gradle dependencies

      # Step 3: Simulate Jenkins using Jenkinsfile Runner Action
      # This action executes the steps defined in your Jenkinsfile
      - name: Run Jenkinsfile Pipeline
        uses: jenkins-infra/jenkinsfile-runner-github-action@v1.0.2 # Or latest version
        with:
          jenkinsfilePath: Jenkinsfile # Tell the action where your Jenkinsfile is located